param([Switch]$Silent)
# =======================================START=OF=COMPILER==========================================================|
#    The Following Code was added by AP-Compiler 1.6 (APC: 1.2) To Make this program independent of AP-Core Engine
#    GitHub: https://github.com/avdaredevil/AP-Compiler
# ==================================================================================================================|
$Script:PSHell=$(if($PSHell){$PSHell}elseif($PSScriptRoot){$PSScriptRoot}else{"."});
$Script:AP_Console = @{version=[version]'1.2'; isShim = $true}
function B64 {param([Parameter(ValueFromPipeline=$true)][String]$Text, [ValidateSet("UTF8","Unicode")][String]$Encoding = "UTF8")     [System.Text.Encoding]::$Encoding.GetString([System.Convert]::FromBase64String($Text))}
# This syntax is to prevent AV's from misclassifying this as anything but innocuous
& (Get-Alias iex) (B64 "ZnVuY3Rpb24gQWRkLVRvUGF0aCB7cGFyYW0oW1ZhbGlkYXRlUGF0dGVybigiLisiKV1bU3RyaW5nXSRGb2xkZXIgPSAkUFdELCBbQWxpYXMoInAiLCJwcmUiLCJiYWNrIildW3N3aXRjaF0kUHJlcGVuZCwgW1N3aXRjaF0kVHJ5LCBbU3dpdGNoXSRGb3JjZSwgW3N0cmluZ10kUGF0aFZhciA9ICJQQVRIIikNCg0KICAgIHRyeSB7DQogICAgICAgICRJc1VuaXggPSAkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICJVbml4Ig0KICAgICAgICBpZiAoISRGb3JjZSkge3RyeSB7JEZvbGRlciA9IFJlc29sdmUtUGF0aCAkRm9sZGVyIC1FcnJvckFjdGlvbiBTdG9wfSBjYXRjaCB7VGhyb3cgIltBUC1QYXRoOkFkZF0gRm9sZGVyIFskRm9sZGVyXSBEb2VzIG5vdCBFeGlzdCJ9fQ0KICAgICAgICBpZiAoISRGb3JjZSAtYW5kIChUZXN0LVBhdGggJGZvbGRlciAtdHlwZSBsZWFmKSkge1Rocm93ICJbQVAtUGF0aDpBZGRdIElucHV0IFskRm9sZGVyXSBtdXN0IGJlIGEgZm9sZGVyISJ9DQogICAgICAgIGlmICgkRm9sZGVyIC1pbiAoR2V0LVBhdGggLVBhdGhWYXIgJFBhdGhWYXIpKSB7cmV0dXJufQ0KICAgICAgICAkUHRoID0gR2V0LUNvbnRlbnQgZW52OlwkUGF0aFZhcg0KICAgICAgICAkRm9sZGVyU2VwID0gJChpZiAoJElzVW5peCkgeyIvIn0gZWxzZSB7IlwifSkNCiAgICAgICAgJFBhdGhTZXAgPSAkKGlmICgkSXNVbml4KSB7IjoifSBlbHNlIHsiOyJ9KQ0KICAgICAgICAkRm9sZGVyID0gJEZvbGRlclswXSArICRGb2xkZXIuU3Vic3RyaW5nKDEpLlRyaW1FbmQoJEZvbGRlclNlcCkNCiAgICAgICAgaWYgKCEkUHJlcGVuZCkgeyRQdGggKz0gIiRQYXRoU2VwJEZvbGRlciJ9IGVsc2UgeyRQdGggPSAiJEZvbGRlciRQYXRoU2VwJCgkUHRoKSJ9DQogICAgICAgIFtFbnZpcm9ubWVudF06OlNldEVudmlyb25tZW50VmFyaWFibGUoJFBhdGhWYXIsICRQdGgpDQogICAgfSBjYXRjaCB7DQogICAgICAgIGlmICgkVHJ5KSB7cmV0dXJufQ0KICAgICAgICBUaHJvdyAkXw0KICAgIH0NCn0KCmZ1bmN0aW9uIEdldC1QYXRoIHtwYXJhbSgkbWF0Y2gsIFtzdHJpbmddJFBhdGhWYXIgPSAiUEFUSCIpDQoNCiAgICAkUHRoID0gW0Vudmlyb25tZW50XTo6R2V0RW52aXJvbm1lbnRWYXJpYWJsZSgkUGF0aFZhcikNCiAgICAkSXNVbml4ID0gJFBTVmVyc2lvblRhYmxlLlBsYXRmb3JtIC1lcSAiVW5peCINCiAgICAkUGF0aFNlcCA9ICQoaWYgKCRJc1VuaXgpIHsiOiJ9IGVsc2UgeyI7In0pDQogICAgaWYgKCEkUHRoKSB7cmV0dXJuIEAoKX0NCiAgICBTZXQtUGF0aCAkUHRoIC1QYXRoVmFyICRQYXRoVmFyDQogICAgJGQgPSAoJFB0aCkuc3BsaXQoJFBhdGhTZXApDQogICAgaWYgKCRtYXRjaCkgeyRkIC1tYXRjaCAkbWF0Y2h9IGVsc2UgeyRkfQ0KfQoKZnVuY3Rpb24gU2V0LVBhdGggew0KICAgIFtjbWRsZXRiaW5kaW5nKCldDQogICAgcGFyYW0oDQogICAgICAgIFtQYXJhbWV0ZXIoTWFuZGF0b3J5ID0gJHRydWUsIFZhbHVlRnJvbVBpcGVsaW5lID0gJHRydWUpXVtzdHJpbmdbXV0kUGF0aCwNCiAgICAgICAgW3N0cmluZ10kUGF0aFZhciA9ICJQQVRIIg0KICAgICkNCiAgICBiZWdpbiB7DQogICAgICAgIFtzdHJpbmdbXV0kRmluYWxQYXRoDQogICAgfQ0KICAgIHByb2Nlc3Mgew0KICAgICAgICAkUGF0aCB8ICUgew0KICAgICAgICAgICAgJEZpbmFsUGF0aCArPSAkXw0KICAgICAgICB9DQogICAgfQ0KICAgIGVuZCB7DQogICAgICAgICRJc1VuaXggPSAkUFNWZXJzaW9uVGFibGUuUGxhdGZvcm0gLWVxICJVbml4Ig0KICAgICAgICAkUGF0aFNlcCA9ICQoaWYgKCRJc1VuaXgpIHsiOiJ9IGVsc2UgeyI7In0pDQogICAgICAgICRQdGggPSAkRmluYWxQYXRoIC1qb2luICRQYXRoU2VwDQogICAgICAgICRQdGggPSAoJFB0aCAtcmVwbGFjZSgiJFBhdGhTZXArIiwgJFBhdGhTZXApIC1yZXBsYWNlKCJcXCRQYXRoU2VwfFxcJCIsICRQYXRoU2VwKSkudHJpbSgkUGF0aFNlcCkNCiAgICAgICAgJFB0aCA9ICgoJFB0aCkuc3BsaXQoJFBhdGhTZXApIHwgc2VsZWN0IC11bmlxdWUpIC1qb2luICRQYXRoU2VwDQogICAgICAgIFtFbnZpcm9ubWVudF06OlNldEVudmlyb25tZW50VmFyaWFibGUoJFBhdGhWYXIsICRQdGgpDQogICAgfQ0KfQoKU2V0LUFsaWFzIEEyUGF0aCBBZGQtVG9QYXRo")
# ========================================END=OF=COMPILER===========================================================|

$PyD = @((item C:\Program*\Oracle\VirtualBox,C:\AP-Progs\Virtua*Box).FullName)[-1]
if (!$PyD) {Throw "VirtualBox Does not Exist on System!";exit}
A2Path $PyD
if (!$Silent) {Write-AP-Wrapper "+Configured Virtual-Box [$(vbox-img.exe -v)] for AP-PShell Management Console!"}
rv PYD

